services:
	front:
		context: ./react
		dockerfile: Dockerfile
		ports:
			- "80:3000"

	nginx:
		image: nginx:latest
		images:
			-./configs/nginx.conf:/etc/nginx/default.conf
		ports:
			- "80:80"
			- "443:443"


			